from stackMin import Stack


def main():
    a = Stack()
    print("pushing 2 ...")
    a.push(2)
    print("Minimun element is:", a.min())
    print()
    print("pushing 4 ...")
    a.push(4)
    print("Minimun element is:", a.min())
    print()
    print("pushing 2 ...")
    a.push(2)
    print("Minimun element is:", a.min())
    print()
    print("pushing 52 ...")
    a.push(52)
    print("Minimun element is:", a.min())
    print()
    print("pushing 133 ...")
    a.push(133)
    print("Minimun element is:", a.min())
    print()
    print("pushing 254...")
    a.push(54)
    print("Minimun element is:", a.min())
    print()
    print("pushing 23 ...")
    a.push(23)
    print("Minimun element is:", a.min())
    print()
    print("pushing 1 ...")
    a.push(1)
    print("Minimun element is:", a.min())
    print()
    print("pushing 1...")
    a.push(1)
    print("Minimun element is:", a.min())
    print()
    print("pushing -1 ...")
    a.push(-1)
    print("Minimun element is:", a.min())
    print()
    print("pushing 4 ...")
    a.push(4)
    print("Minimun element is:", a.min())
    print()
    print("pushing 2 ...")
    a.push(2)
    print("Minimun element is:", a.min())
    print()

    print("Pop...", a.pop())
    print("Minimun element is:", a.min())
    print()

    print("Pop...", a.pop())
    print("Minimun element is:", a.min())
    print()

    print("Pop...", a.pop())
    print("Minimun element is:", a.min())
    print()

    print("Pop...", a.pop())
    print("Minimun element is:", a.min())
    print()

    print("Pop...", a.pop())
    print("Minimun element is:", a.min())
    print()


if __name__ == "__main__":
    main()
